name: afib
channels:
  - conda-forge
dependencies:
  - numpy
  - scikit-learn
  - wfdb
  - tqdm
  - py-xgboost
  - catboost
  - lightgbm
  - matplotlib
  - ipykernel
  - ca-certificates
  - certifi
  - openssl
  - ipywidgets=7.7.1
  - fastparquet
  - msgpack-python